-d /home/akiel/trunk/pub/cortexm1_clone/boards/gw5a25/impl/gwsynthesis/m1_soc.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst /home/akiel/trunk/pub/cortexm1_clone/boards/gw5a25/pins.cst
-cfg /home/akiel/trunk/pub/cortexm1_clone/boards/gw5a25/impl/pnr/device.cfg
-sdc /home/akiel/trunk/pub/cortexm1_clone/boards/gw5a25/timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
